spring.application.name=reservacion-coworking

spring.datasource.url=jdbc:postgresql://localhost:5432/db_coworking

spring.datasource.username=postgres
spring.datasource.password=password

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update

# Formatea el SQL en la consola para que sea legible
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false
springdoc.api-docs.enabled=false
springdoc.swagger-ui.enabled=false